server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: usuarios-route
            uri: lb://msvc-usuarios
            predicates:
              - Path=/api/usuarios/**
          - id: cuentas-route
            uri: lb://msvc-usuarios
            predicates:
              - Path=/api/cuentas/**
          - id: monopatines-route
            uri: lb://msvc-flota
            predicates:
              - Path=/api/monopatines/**
          - id: paradas-route
            uri: lb://msvc-flota
            predicates:
              - Path=/api/paradas/**
          - id: facturacion-route
            uri: lb://msvc-facturacion
            predicates:
              - Path=/api/facturacion/**
          - id: transacciones-route
            uri: lb://msvc-facturacion
            predicates:
              - Path=/api/transacciones/**
          - id: mercado-pago-route
            uri: lb://msvc-facturacion
            predicates:
              - Path=/api/mercado-pago/cobrar
          - id: tarifas-route
            uri: lb://msvc-tarifas
            predicates:
              - Path=/api/tarifas/**
          - id: viajes-route
            uri: lb://msvc-viajes
            predicates:
              - Path=/api/viajes/**
          - id: pausas-route
            uri: lb://msvc-viajes
            predicates:
              - Path=/api/pausas/**
          - id: reportes-route
            uri: lb://msvc-reportes
            predicates:
              - Path=/api/reportes/**
          - id: groq-route
            uri: lb://msvc-groq
            predicates:
              - Path=/api/chatbot/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

jwt:
  secret: miClaveSecretaSuperSeguraDeAlMenos256Bits1234567890
  expiration: 3600000