server:
  port: 8086

spring:
  application:
    name: msvc-tarifas
  datasource:
    url: jdbc:postgresql://localhost:5432/msvc_tarifas
    username: mateo
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
