server:
  port: 8099

groq:
  api-key: ${GROQ_API_KEY}
  base-url: https://api.groq.com/openai/v1
  model: llama3-70b-8192
  temperature: 0.3
  max-tokens: 2048

spring:
  application:
    name: msvc-groq
  ai:
    chat:
      model: ${groq.model}
      options:
        temperature: ${groq.temperature}
