server:
  port: 8083

spring:
  application:
    name: msvc-flota
  data:
    mongodb:
      uri: mongodb://mateo:secret@localhost:27017/msvc-flota?authSource=admin
  cloud:
    openfeign:
      httpclient:
        enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/